### ISSUE TITLE
Feature request: pulling in post title and tags

### ISSUE THREAD

**Issue by michaelchadwick** [cbrgm/contributing#1]
First of all, thanks for the useful Github Action. I'm currently using it on my Mastodon instance to post my blog's new entries.

Would it be possible to add the ability to pull in the title of the blog post so that I can display it on the Mastodon post? Also, would it be possible to pull in the tags on my blog post (done in Jekyll) so they appear on my Mastodon post, as well?

Thanks!

**Comment by cbrgm** [comment]
Hey @michaelchadwick, 

I guess you can open up this issue on the mastodon action repository as well so it's visible for others. So there's no integration for Jekyll if I got you right. It's possible to use GitHub variables in a multiline message like here https://github.com/michaeljaggers/oh-my-posh/blob/d34d9d368c1b74b12734dfb552ab711ab7d0ade1/.github/workflows/mastodon.yml#L27

I think this already offers a lot of flexibility as you could in theory add all kinds of things to variables and use them in the templated message being sent to Mastodon via this GitHub action.
